version: "3"
services:
  hmis-interop:
    container_name: hmis-interop
    image: kuunika/hmis-interop
    restart: always

    environment:
      - API_BASE_URL=${HMIS_API_BASE_URL}
      - API_USERNAME=${HMIS_API_USERNAME}
      - API_PASSWORD=${HMIS_API_PASSWORD}
      - API_PORT=${HMIS_API_PORT}
      - API_GLOBAL_BASE_URL=${HMIS_API_GLOBAL_BASE_URL}

    ports:
      - "${HMIS_API_PORT}:${HMIS_API_PORT}"

  nlims-mediator:
    container_name: nlims-mediator
    image: kuunika/nlims-mediator
    restart: always

    environment:
      - LIMS_API_HOST=${LIMS_API_HOST}
      - LIMS_API_TOKEN=${LIMS_API_TOKEN}
    ports:
      - "${NLIMS_MEDIATOR_PORT}:${NLIMS_MEDIATOR_PORT}"

  ohsp-interop:
    container_name: ohsp-interop
    image: kuunika/ohsp-interop
    restart: always

    environment:
      - OHSP_BASE_URL=${OHSP_BASE_URL}
      - OHSP_USERNAME=${OHSP_USERNAME}
      - OHSP_PASSWORD=${OHSP_PASSWORD}
      - COVID_DASHBOARD_API_URL=${COVID_DASHBOARD_API_URL}
    ports:
      - "${OHSP_API_PORT}:${OHSP_API_PORT}"
